services:
  cerberus-be:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/cerberus-be:latest
    container_name: dev-app-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=cerberus
      - DB_USER=postgres
      - DB_PASSWORD=qwe123
    networks:
      - web-network

networks:
  web-network:
    external: true