spring:
  application:
    name: demo
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#jwt:
#  access:
#    expiration: 10800000
#    header: AccessToken
#  refresh:
#    expiration: 604800000
#  secretKey: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true