spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # ai:
  #   openai:
  #     api-key: ${OPENAI_API_KEY:your_api_key_here}
  #     chat:
  #       options:
  #         model: gpt-4o-mini

server:
  forward-headers-strategy: framework

file:
  upload-dir: ./uploads

#jwt:
#  access:
#    expiration: 10800000
#    header: AccessToken
#  refresh:
#    expiration: 604800000
#  secretKey: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true